typos and docs improved
UCL-BLIC/DGE pull request #2
Opened 2022-05-31 11:41 UTC by colindaven

2022-05-31 13:28 UTC, jherrero approved these changes

2022-05-31 13:46 UTC, jherrero requested changes
Thank you for spotting the typos and for suggesting style changes.

The general.config file does not seem to be very generic as it tries to submit jobs to the "bioinformatics" queue, which is a site-specific thing. Although the default executor is "local", so the queue probably doesn't matter anyway. However, the location of the genome annotation files is still UCL-specific.

If you can make it more generic, we will be happy to merge the changes. Otherwise, if you prefer to have something specific to your environment, you can name the config file with a more specific name.

2022-05-31 14:25 UTC, colindaven commented
No problem, gladly. Yes, it's not really general yet. 

I'm not looking to use the GSEA (it's not human data) or Kallisto so think a docs change to set the hard coded paths might be a better idea. 

I just want to use the DESeq2 part with nextflow, and will be trying to implement and test this in the coming weeks.

Thanks

2022-06-07 07:04 UTC, colindaven commented
I changed the config from general to local.config.

I have managed to successfully implement a pipeline version locally, which works nicely - thanks. 

I might supply an R script which may help others to install the R packages as an issue, since this is undocumented.

2022-06-30 10:02 UTC, merged